version: '3.6'

#Docker services
services:
  db:
    image: postgres:12
    restart: always
    ports:
      - "5555:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./.containers/postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=db
      - PGDATA=/var/lib/postgresql/data/db-files/
    networks:
      - application

  app:
    build:
      context: .
    networks:
      - application
    ports:
      - 9000:9000
      - 5173:5173
    volumes:
      - ./src:/var/www
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 9999:80
    volumes:
      - ./src/:/var/www
      - ./.docker/nginx/:/etc/nginx/conf.d/
    networks:
      - application
    depends_on:
      - app

networks:
  application:
    name: application
    driver: bridge

volumes:
  db_data:
    driver: local
